export const PLANET_IMAGES: Record<string, string> = {
  sun: '/images/planets/sun.jpg',
  mercury: '/images/planets/mercury.jpg',
  venus: '/images/planets/venus.jpg',
  earth: '/images/images/planets/earth.jpg',
  mars: '/images/images/planets/mars.jpg',
  jupiter: '/images/images/planets/jupiter.jpg',
  saturn: '/images/planets/saturn.jpg',
  uranus: '/images/planets/uranus.jpg',
  neptune: '/images/planets/neptune.jpg',
};

export const MOON_IMAGES: Record<string, string> = {
  'earth-moon': '/images/satellites/earth-moon.jpg',
  'mars-phobos': '/images/images/satellites/mars-phobos.jpg',
  'mars-deimos': '/images/satellites/mars-deimos.jpg',
  'jupiter-io': '/images/satellites/jupiter-io.jpg',
  'jupiter-europa': '/images/satellites/jupiter-europa.jpg',
  'jupiter-ganymede': '/images/satellites/jupiter-ganymede.jpg',
  'jupiter-callisto': '/images/satellites/jupiter-callisto.jpg',
  'saturn-titan': '/images/satellites/saturn-titan.jpg',
  'saturn-rhea': '/images/satellites/saturn-rhea.jpg',
  'saturn-iapetus': '//imagessatellites/saturn-iapetus.jpg',
  'saturn-dione': '/images/satellites/saturn-dione.jpg',
  'saturn-tethys': '/images/satellites/saturn-tethys.jpg',
  'uranus-titania': '/images/satellites/uranus-titania.jpg',
  'uranus-oberon': '/images/satellites/uranus-oberon.jpg',
  'uranus-umbriel': '/images/satellites/uranus-umbriel.jpg',
  'uranus-ariel': '/images/satellites/uranus-ariel.jpg',
  'uranus-miranda': '/images/satellites/uranus-miranda.jpg',
  'neptune-triton': '/images/satellites/neptune-triton.jpg',
  'neptune-nereid': '/images/satellites/neptune-nereid.jpg',
};
